218/oi/agenda/config/routes.rb
Rails.application.routes.draw do
  get 'manda/index'
  resources :atividades
  root 'manda#index'
  get 'index' => 'avisos#index'
  post 'atividades/new', to: 'atividades#new'
  resources :avisos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

218/oi/agenda/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

218/oi/agenda/app/models/atividade.rb
class Atividade < ApplicationRecord
    validates_presence_of :nome, :sala, :professor, :horario_inicio, :horario_fim
    validate :conflitos
    validate :horarios

    private

    def conflitos
        atividades = Atividade.all

        atividades.each do |atv|
            if atv.id != id # que nao seja a atividade que estamos inserindo
                # checa se tem mais de uma atividade ao mesmo tempo na sala
                if atv.sala == sala
                    if atv.horario_fim > horario_inicio and atv.horario_inicio < horario_fim
                        errors.add(atv.nome,  "ja acontecerá nessa sala e nesse horario!")
                    end
                # checa se o professor esta em duas aulas ao mesmo tempo
                elsif atv.professor == professor
                    if atv.horario_fim > horario_inicio and atv.horario_inicio < horario_fim
                        errors.add(atv.horario_inicio.to_s, atv.professor + " está ocupado nesse horario!")
                    end
                end
            end
        end
    end

    def horarios
        if horario_inicio != nil and horario_fim != nil
            if horario_inicio >= horario_fim
                errors.add(nome,  "possui horários inválidos!")
            end
        end
    end
end

218/oi/agenda/app/models/aviso.rb
class Aviso < ApplicationRecord
  validates :body, presence: true, length: {maximum: 50} 
  validates :title, presence: true, length: {maximum: 20}
end

218/oi/agenda/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

218/oi/agenda/app/controllers/atividades_controller.rb
class AtividadesController < ApplicationController
    def create
        @atividade = Atividade.new(
             params.require(:atividade).permit(:nome, :horario_inicio, :horario_fim, :sala, :professor))
        # salva
        @atividade.save
        #testamos o salva
        if @atividade.save
            # mostra
            redirect_to @atividade
        else
            render 'new'
        end
    end

    def new
        @atividade = Atividade.new
    end

    def show
        @atividade = Atividade.find(params[:id])
    end

    def index
        @atividades = Atividade.all
    end

    def destroy
        @atividade = Atividade.find(params[:id])
        if @atividade.destroy
            flash[:notice] = "bye bye atividade!"
        end

        redirect_to atividades_path
    end

    def edit
        @atividade = Atividade.find(params[:id])
    end

    def update
        @atividade = Atividade.find(params[:id])
        if @atividade.update(atividades_params)
            redirect_to @atividade
        else
            render 'edit'
        end
    end

    private
    def atividades_params
       params.require(:atividade).permit(:nome, :horario_inicio, :horario_fim, :sala, :professor)
    end
end

218/oi/agenda/app/controllers/avisos_controller.rb
class AvisosController < ApplicationController
  def index
    @title = 'Mural de avisos';
    @avisos = Aviso.all
  end

  def new
    @aviso = Aviso.new
  end

  def show
    @aviso = Aviso.find(params[:id])
  end

  def update
    @aviso = Aviso.find(params[:id])
    if(@aviso.update(aviso_params))
      redirect_to @aviso
    else
      render 'edit'
    end
  end

  def destroy
    @aviso = Aviso.find(params[:id])
    @aviso.destroy

    redirect_to avisos_path
  end

  def edit
    @aviso = Aviso.find(params[:id])
  end

  def create
    # render plain: params[:aviso].inspect
    @aviso = Aviso.new(aviso_params)

    if(@aviso.save)
      redirect_to @aviso
    else
      render 'new'
    end
  end

  private def aviso_params
    params.require(:aviso).permit(:title, :body)
  end
end

218/oi/agenda/app/controllers/manda_controller.rb
class MandaController < ApplicationController
  def index
  end
end

218/oi/agenda/app/helpers/application_helper.rb
module ApplicationHelper
end

218/oi/agenda/app/helpers/atividades_helper.rb
module AtividadesHelper
end

218/oi/agenda/app/helpers/avisos_helper.rb
module AvisosHelper
end

218/oi/agenda/app/helpers/manda_helper.rb
module MandaHelper
end

218/oi/agenda/app/views/atividades/_formulario.html.haml
= form_with model: @atividade, local: true  do |f|
    - if @atividade.errors.any?
        %ul.list
        - @atividade.errors.full_messages.each do |msg|
            %li.list= msg
    %table
        %tr
            %td
                = f.label :nome
            %td
                = f.text_field :nome
        %tr
            %td
                = f.label :horario_inicio
            %td
                = f.text_field :horario_inicio
        %tr
            %td
                = f.label :horario_fim
            %td
                = f.text_field :horario_fim
        %tr
            %td
                = f.label :sala
            %td
                = f.text_field :sala
        %tr
            %td
                = f.label :professor
            %td
                = f.text_field :professor

    = f.submit t(:save), class: "button"
    = link_to 'Voltar', atividades_path, class: "button buttonBack"

218/oi/agenda/app/views/atividades/application.html.haml
!!!
%html
    %head
        %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
        %title Agenda
        = csrf_meta_tags
        = csp_meta_tag
        = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
        = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %body
        %nav.navbar.navbar-default.container-fluid
            .collapse.navbar-collapse
                .navbar.navbar-nav.navbar-right
                    .btn= link_to t(:list), atividades_path
                    .btn= link_to t(:new), new_atividade_path
        = yield

218/oi/agenda/app/views/atividades/edit.html.haml
%center
    %h1 Editando uma atividade
    = render 'formulario'

218/oi/agenda/app/views/atividades/index.html.haml
%center
    %ul
        %li.home
            %a{:href => "../"} Home
        %li.home
            %a.active{:href => "atividades"} Atividades
        %li.home
            %a{:href => "avisos"} Mural de avisos
    %h2.subtitulo=t(:list)
    %table{border: 2}
        %tr
            %th Nome
            %th Horario de início
            %th Horario de fim
            %th Sala
            %th Professor
            %th
            %th

        - @atividades.each do |at|
            %tr
                %td= at.nome
                %td= at.horario_inicio
                %td= at.horario_fim
                %td= at.sala
                %td= at.professor
                %td
                    = link_to t(:edit), edit_atividade_path(at),
                    class: "button buttonEdit"
                    %span.glyphicon.glyphicon-pencil
                %td
                    = link_to t(:delete), atividade_path(at), method: :delete,
                    data: {confirm: 'Deseja mesmo apagar essa atividade?'},
                    class: "button buttonDelete"
    = link_to 'Nova atividade', new_atividade_path, class: "button buttonNew"

218/oi/agenda/app/views/atividades/new.html.haml
%center
    %h1 Nova atividade
    = render 'formulario'

218/oi/agenda/app/views/atividades/show.html.haml
%center
    %h1 Atividade inserida com sucesso!
    %p
        %i= @atividade.nome
        começa às
        %i= @atividade.horario_inicio
        termina às
        %i= @atividade.horario_fim
    %p
        será na sala
        %i= @atividade.sala
    %p
        e será ministrada pelo professor
        %i= @atividade.professor
    %p
        = link_to 'Editar', edit_atividade_path(@atividade), class: "button"
        = link_to 'Novo',   new_atividade_path, class: "button"
        = link_to 'Início',  atividades_path, class: "button"

218/oi/agenda/app/views/avisos/edit.html.haml
%center
	%h1 Editando aviso
	= form_for :aviso, url: aviso_path(@aviso), method: :patch do |f|
		- if @aviso.errors.any?
			- @aviso.errors.full_messages.each do |m|
				.alert.alert-danger= m
		%table
			%tr
				%td
					= f.label :title
				%td
					= f.text_field :title
			%tr
				%td
					= f.label :body
				%td
					= f.text_area :body

		= f.submit({:class => "button"})
		= link_to 'Voltar', avisos_path, class: "button buttonBack"

218/oi/agenda/app/views/avisos/index.html.haml
%center
	%ul
		%li
			%a{:href => "../"} Home
		%li
			%a{:href => "../atividades"} Atividades
		%li
			%a.active{:href => "../avisos"} Mural de avisos
	%h2 Avisos importantes
	%table{border: 2}
		%tr
			%th Título
			%th Corpo
			%th 
			%th 

		- @avisos.each do |aviso|
			%tr
				%td= aviso.title
				%td= aviso.body
				%td
					= link_to "Editar", edit_aviso_path(aviso),
					class: "button buttonEdit"
					%span.glyphicon.glyphicon-pencil
				%td
					= link_to "Apagar", aviso_path(aviso), method: :delete,
					data: {confirm: 'Deseja mesmo apagar esse aviso?'},
					class: "button buttonDelete"
				/%td
				/	= link_to "Aviso completo", aviso_path(aviso), 
				/	class: "button buttonEdit"

	= link_to 'Novo aviso', new_aviso_path, class: "button buttonNew"

218/oi/agenda/app/views/avisos/new.html.haml
%center
	%h1 Adicionando aviso
	= form_for :aviso, url: avisos_path(@aviso)do |f|
		- if @aviso.errors.any?
			- @aviso.errors.full_messages.each do |m|
				.alert.alert-danger= m
		%table
			%tr
				%td
					= f.label :title
				%td
					= f.text_field :title
			%tr
				%td
					= f.label :body
				%td
					= f.text_area :body

		= f.submit({:class => "button"})
		= link_to 'Voltar', avisos_path, class: "button buttonBack"

218/oi/agenda/app/views/avisos/show.html.haml
%center
	%h1 Aviso inserido com sucesso!
	%p
		%i= @aviso.title
		com descrição:
	%p
		%i= @aviso.body

	%hr/
	= link_to 'Editar', edit_aviso_path(@aviso), class: "button"
	= link_to 'Novo',   new_aviso_path, class: "button"
	= link_to 'Início',  avisos_path, class: "button"

218/oi/agenda/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Agenda
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

218/oi/agenda/app/views/manda/index.html.haml
%ul
	%li
		%a.active{:href => ""} Home
	%li
		%a{:href => "atividades"} Atividades
	%li
		%a{:href => "avisos"} Mural de avisos
%h2
%center
	%img{:src => "https://cdn.discordapp.com/attachments/559586799488466990/592985145246744576/unknown.png",
		:style=>"width:50%;"}
	%h2
	%h2 	O objetivo desse site é disponibilizar um mapa do IME que mostre
	%h2 todas as salas, especificando o professor, horário e aula que está
	%h2 ocorrendo naquele momento. Além disso, disponibilizar um mural de
	%h2 avisos, contendo informações relevantes para os imeanos :)